/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2025-05-06 23:29:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Student Profile | goSJSU</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/modern-dashboard.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"dashboard-container\">\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <aside class=\"sidebar\">\n");
      out.write("      <div class=\"sidebar-header\">\n");
      out.write("        <div class=\"logo\">\n");
      out.write("          <div class=\"logo-icon\">\n");
      out.write("            <div class=\"logo-square light\"></div>\n");
      out.write("            <div class=\"logo-square dark\"></div>\n");
      out.write("          </div>\n");
      out.write("          <h1>goSJSU</h1>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <nav class=\"sidebar-nav\">\n");
      out.write("        <ul>\n");
      out.write("          <li class=\"nav-item\" data-section=\"dashboard\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/dashboard?studentId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("              <i class=\"fas fa-th-large\"></i>\n");
      out.write("              <span>Dashboard</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item active\" data-section=\"profile\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/profile.jsp?studentId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("              <i class=\"fas fa-user\"></i>\n");
      out.write("              <span>Profile</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" data-section=\"registration\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/registration?studentId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("              <i class=\"fas fa-calendar-alt\"></i>\n");
      out.write("              <span>Registration</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" data-section=\"timetable\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/dashboard?studentId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("#timetable\">\n");
      out.write("              <i class=\"fas fa-clock\"></i>\n");
      out.write("              <span>Timetable</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" data-section=\"grades\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/student/dashboard?studentId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("#grades\">\n");
      out.write("              <i class=\"fas fa-graduation-cap\"></i>\n");
      out.write("              <span>Grades</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" data-section=\"logout\">\n");
      out.write("            <a href=\"#\" id=\"logoutLink\">\n");
      out.write("              <i class=\"fas fa-sign-out-alt\"></i>\n");
      out.write("              <span>Logout</span>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </nav>\n");
      out.write("    </aside>\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <main class=\"main-content\">\n");
      out.write("      <!-- Header -->\n");
      out.write("      <header class=\"dashboard-header\">\n");
      out.write("        <h1>Profile</h1>\n");
      out.write("        <div class=\"date\" id=\"currentDate\"></div>\n");
      out.write("      </header>\n");
      out.write("      \n");
      out.write("      <div class=\"profile-container\" style=\"background-color: var(--surface); border-radius: var(--radius-md); box-shadow: var(--shadow); padding: 0; overflow: hidden;\">\n");
      out.write("        <div class=\"profile-banner\" style=\"position: relative; height: 200px; background: linear-gradient(135deg, #4338ca, #ec4899);\">\n");
      out.write("          <div class=\"profile-banner-img\"></div>\n");
      out.write("          <div class=\"profile-avatar-container\" style=\"position: absolute; bottom: -40px; left: 50%; transform: translateX(-50%); width: 120px; height: 120px; border-radius: 50%; border: 4px solid var(--surface); overflow: hidden; background-color: var(--surface);\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/profile-avatar.jpg\" alt=\"Profile avatar\" class=\"profile-avatar\" onerror=\"this.src='https://via.placeholder.com/120x120?text=MJ'\" style=\"width: 100%; height: 100%; object-fit: cover;\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"profile-info\" style=\"text-align: center; padding: 3rem 2rem 2rem;\">\n");
      out.write("          <h2 class=\"profile-name\" style=\"font-size: 1.5rem; font-weight: 700; margin-bottom: 0.25rem;\">Marlon</h2>\n");
      out.write("          <p class=\"profile-email\" style=\"font-size: 0.875rem; color: var(--text-secondary); margin-bottom: 0.5rem;\">marlon.burog@sjsu.edu</p>\n");
      out.write("          <p class=\"profile-major\" style=\"font-size: 1rem; font-weight: 500; color: var(--primary); margin-bottom: 1.5rem;\">Software Engineer</p>\n");
      out.write("          \n");
      out.write("          <div class=\"profile-stats\" style=\"display: flex; justify-content: center; gap: 4rem; margin-bottom: 2rem;\">\n");
      out.write("            <div class=\"stat-item\" style=\"text-align: center;\">\n");
      out.write("              <h3 style=\"font-size: 1.25rem; font-weight: 700; margin-bottom: 0.25rem;\">Year 3</h3>\n");
      out.write("              <p style=\"font-size: 0.875rem; color: var(--text-secondary);\">Current Year</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-item\" style=\"text-align: center;\">\n");
      out.write("              <h3 style=\"font-size: 1.25rem; font-weight: 700; margin-bottom: 0.25rem;\">123456789</h3>\n");
      out.write("              <p style=\"font-size: 0.875rem; color: var(--text-secondary);\">Student ID</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"profile-section\" style=\"background-color: var(--profile-section-bg, #f8fafc); border: 1px solid var(--profile-section-border, #e2e8f0); border-radius: var(--radius-md); padding: 1.5rem; margin-bottom: 1.5rem; text-align: left;\">\n");
      out.write("            <h3 class=\"section-title\" style=\"font-size: 1.125rem; font-weight: 600; margin-bottom: 1.25rem; color: var(--text-primary); position: relative; padding-left: 1rem; border-left: 3px solid var(--primary);\">Personal</h3>\n");
      out.write("            <div class=\"profile-details\" style=\"display: flex; flex-direction: column; gap: 1.5rem;\">\n");
      out.write("              <div class=\"detail-row\" style=\"display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem;\">\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">First name</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">MJ</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Major</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">Software Engineer</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Gender</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">Male</p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"detail-row\" style=\"display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem;\">\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Last Name</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">Marlon Burog</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Date of Birth</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">01/01/2001</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">City</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">San Jose</p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"profile-section\" style=\"background-color: var(--profile-section-bg, #f8fafc); border: 1px solid var(--profile-section-border, #e2e8f0); border-radius: var(--radius-md); padding: 1.5rem; margin-bottom: 1.5rem; text-align: left;\">\n");
      out.write("            <h3 class=\"section-title\" style=\"font-size: 1.125rem; font-weight: 600; margin-bottom: 1.25rem; color: var(--text-primary); position: relative; padding-left: 1rem; border-left: 3px solid var(--primary);\">Contact</h3>\n");
      out.write("            <div class=\"profile-details\" style=\"display: flex; flex-direction: column; gap: 1.5rem;\">\n");
      out.write("              <div class=\"detail-row\" style=\"display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem;\">\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Email</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">Marlon.Burog@sjsu.edu</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"detail-item wide\" style=\"display: flex; flex-direction: column; gap: 0.5rem; grid-column: span 2;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Postal Address</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">6969 Farpost CT<br>San Jose, CA 95121</p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"detail-row\" style=\"display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem;\">\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Mobile Number</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">0234567891</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"detail-item\" style=\"display: flex; flex-direction: column; gap: 0.5rem;\">\n");
      out.write("                  <label style=\"font-size: 0.75rem; color: var(--text-secondary); font-weight: 500;\">Alternate Mobile Number</label>\n");
      out.write("                  <p style=\"font-size: 0.875rem; font-weight: 500;\">0509876543</p>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </main>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Logout Confirmation Modal -->\n");
      out.write("  <div id=\"logoutModal\" class=\"modal\">\n");
      out.write("    <div class=\"modal-content logout-modal\">\n");
      out.write("      <div class=\"logout-header\">\n");
      out.write("        <h2>Confirm Logout</h2>\n");
      out.write("        <span class=\"close-modal\" id=\"closeLogoutModal\">&times;</span>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"logout-body\">\n");
      out.write("        <p>Are you sure you want to log out of your account?</p>\n");
      out.write("        <div class=\"logout-actions\">\n");
      out.write("          <button class=\"logout-cancel-btn\">Cancel</button>\n");
      out.write("          <button class=\"logout-confirm-btn\">Logout</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    // Set current date\n");
      out.write("    function setCurrentDate() {\n");
      out.write("      const dateOptions = { \n");
      out.write("        weekday: 'long', \n");
      out.write("        year: 'numeric', \n");
      out.write("        month: 'long', \n");
      out.write("        day: 'numeric' \n");
      out.write("      };\n");
      out.write("      const currentDate = new Date().toLocaleDateString('en-US', dateOptions);\n");
      out.write("      \n");
      out.write("      document.getElementById('currentDate').innerText = currentDate;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("      setCurrentDate();\n");
      out.write("      \n");
      out.write("      // Logout Modal\n");
      out.write("      const logoutModal = document.getElementById('logoutModal');\n");
      out.write("      const logoutLink = document.getElementById('logoutLink');\n");
      out.write("      const closeLogoutModal = document.getElementById('closeLogoutModal');\n");
      out.write("      const cancelLogoutBtn = document.querySelector('.logout-cancel-btn');\n");
      out.write("      const confirmLogoutBtn = document.querySelector('.logout-confirm-btn');\n");
      out.write("      \n");
      out.write("      // Open logout modal when logout link is clicked\n");
      out.write("      logoutLink.addEventListener('click', function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        logoutModal.style.display = 'block';\n");
      out.write("        document.body.classList.add('modal-open');\n");
      out.write("      });\n");
      out.write("      \n");
      out.write("      // Close logout modal\n");
      out.write("      function closeLogoutModalFunc() {\n");
      out.write("        logoutModal.style.display = 'none';\n");
      out.write("        document.body.classList.remove('modal-open');\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      // Close modal when X is clicked\n");
      out.write("      closeLogoutModal.addEventListener('click', closeLogoutModalFunc);\n");
      out.write("      \n");
      out.write("      // Close modal when Cancel is clicked\n");
      out.write("      cancelLogoutBtn.addEventListener('click', closeLogoutModalFunc);\n");
      out.write("      \n");
      out.write("      // Handle logout confirmation\n");
      out.write("      confirmLogoutBtn.addEventListener('click', function() {\n");
      out.write("        window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\";\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
